apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-operator"
  labels:
    {{- include "legion.helm-labels" (dict "component" "operator" "root" .) | nindent 4 }}
spec:
  serviceName: "legion-operator"
  replicas: {{ .Values.operator.server.replicas }}
  selector:
    matchLabels:
      {{- include "legion.helm-labels-for-search" (dict "component" "operator" "root" .) | nindent 6 }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        {{- include "legion.helm-labels" (dict "component" "operator" "root" .) | nindent 8 }}
    spec:
      {{- if .Values.rbac }}
      serviceAccountName: "{{ .Release.Name }}-operator"
      {{- end }}
      containers:
      - image: "{{ include "legion.image-name" (dict "root" . "service" .Values.operator.server "tpl" "%sk8s-operator:%s") }}"
        imagePullPolicy: Always
        name: operator
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: BUILDER_IMAGE
            value: "{{ include "legion.image-name" (dict "root" . "service" .Values.operator.builder "tpl" "%sk8s-model-builder:%s") }}"
          - name: BUILDER_SERVICE_ACCOUNT
            value: "{{ .Release.Name }}-model-builder"
          - name: BUILD_IMAGE_PREFIX
            value: {{ .Values.modelStorage.buildPrefix | quote }}
          - name: DOCKER_REGISTRY
            value: {{ .Values.modelStorage.external.url | quote }}
          - name: DOCKER_REGISTRY_USER
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-operator-config"
                key: docker.registry.user
          - name: DOCKER_REGISTRY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-operator-config"
                key: docker.registry.password
          - name: MODEL_CLUSTER_TRAIN_METRICS_ENABLED
            value: "{{ .Values.modelMetrics.enabled }}"
          - name: METRICS_HOST
            value: {{ .Values.modelMetrics.host | quote }}
          - name: METRICS_PORT
            value: {{ .Values.modelMetrics.port | quote }}
          - name: PROMETHEUS_METRICS_PORT
            value: "7777"
          - name: JWT_ENABLED
            value: {{ .Values.modelApiSecurity.enabled | quote }}
          - name: JWKS_URL
            value: "http://{{ .Release.Name }}-edi.{{ .Release.Namespace }}.svc.cluster.local/api/v1/model/jwks"
          - name: JWKS_CLUSTER
            value: "outbound|80||{{ .Release.Name }}-edi.{{ .Release.Namespace }}.svc.cluster.local"
          - name: EDGE_HOST
            value: https://{{ include "legion.ingress-domain-name" (dict "local" .Values.edge.ingress "root" . "tpl" "edge.%s") }}
        resources:
          {{- toYaml .Values.operator.server.resources | nindent 10 }}
        ports:
        - containerPort: 7777
          name: metrics
          protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-operator-config"
  labels:
    {{- include "legion.helm-labels" (dict "component" "operator" "root" .) | nindent 4 }}
data:
  docker.registry.user: {{ .Values.modelStorage.external.user | b64enc | quote }}
  docker.registry.password: {{ .Values.modelStorage.external.password | b64enc | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-operator"
  labels:
    {{- include "legion.helm-labels" (dict "component" "operator" "root" .) | nindent 4 }}
spec:
  selector:
    {{- include "legion.helm-labels-for-search" (dict "component" "operator" "root" .) | nindent 4 }}
  ports:
  - name: metrics
    targetPort: 7777
    port: 7777
    protocol: TCP
