apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-webhook-server"
  labels:
    {{- include "legion.helm-labels" (dict "component" "legion-webhook-server" "root" .) | nindent 4 }}
spec:
  replicas: {{ .Values.webhook.server.replicas }}
  selector:
    matchLabels:
      {{- include "legion.helm-labels-for-search" (dict "component" "legion-webhook-server" "root" .) | nindent 6 }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        {{- include "legion.helm-labels" (dict "component" "legion-webhook-server" "root" .) | nindent 8 }}
    spec:
      {{- if .Values.rbac }}
      serviceAccountName: "{{ .Release.Name }}-operator"
      {{- end }}
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: "{{ .Release.Name }}-webhook-server-secret"
      containers:
      - image: "{{ include "legion.image-name" (dict "root" . "service" .Values.webhook.server "tpl" "%swebhook-server:%s") }}"
        imagePullPolicy: Always
        name: webhook-server
        volumeMounts:
          - mountPath: /tmp/cert
            name: cert
            readOnly: true
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: WEBHOOK_SECRET_NAME
            value: "{{ .Release.Name }}-webhook-server-secret"
          - name: WEBHOOK_SERVICE_NAME
            value: "{{ .Release.Name }}-webhook-server"
          - name: WEBHOOK_PORT
            value: "9876"
          - name: PROMETHEUS_METRICS_PORT
            value: "7777"
          - name: PYTHON_TOOLCHAIN_IMAGE
            value: "{{ include "legion.image-name" (dict "root" . "service" .Values.toolchains.python "tpl" "%spython-toolchain:%s") }}"
        resources:
          {{- toYaml .Values.webhook.server.resources | nindent 10 }}
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        - containerPort: 7777
          name: metrics
          protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "legion.helm-labels" (dict "component" "legion-webhook-server" "root" .) | nindent 4 }}
  name: "{{ .Release.Name }}-webhook-server-secret"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-webhook-server"
  labels:
    {{- include "legion.helm-labels" (dict "component" "legion-webhook-server" "root" .) | nindent 4 }}
spec:
  selector:
    {{- include "legion.helm-labels-for-search" (dict "component" "legion-webhook-server" "root" .) | nindent 4 }}
  ports:
  - name: metrics
    targetPort: 7777
    port: 7777
    protocol: TCP
  - name: webhook
    targetPort: 9876
    port: 443
    protocol: TCP