{{- if .Values.edi.enabled -}}
{{- if .Values.modelApiSecurity.enabled }}
{{- if eq .Values.modelApiSecurity.integration "jwt" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-edi-keys"
  labels:
        {{- include "legion.helm-labels" (dict "component" "fluentd" "root" .) | nindent 4 }}
type: Opaque
data:
  private.pem: "{{ .Values.modelApiSecurity.jwt.private_key }}"
  public.pem: "{{ .Values.modelApiSecurity.jwt.public_key }}"
{{- end }}
{{- end }}
{{- end }}