apiVersion: legion.legion-platform.org/v1alpha1
kind: ModelTraining
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  annotations:
    version: "1.1"
    name: summation
  name: test-summation
spec:
  toolchain: jupyter
  vcsName: legion
  workDir: "examples/Test-Summation"
  entrypoint: "Summation.ipynb"
  resources:
    requests:
      memory: 128Mi
      cpu: 128m
    limits:
      memory: 256Mi
      cpu: 256m