apiVersion: legion.legion-platform.org/v1alpha1
kind: ModelTraining
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  annotations:
    version: "1.1"
    name: income-prediction
  name: sklearn-income-training
spec:
  toolchain: jupyter
  vcsName: legion
  workDir: "examples/Sklearn-Income"
  entrypoint: "Income-wo-df.ipynb"
  resources:
    requests:
      memory: 128Mi
      cpu: 128m
    limits:
      memory: 256Mi
      cpu: 256m
  data:
  - connection: <Connection Name>
    localPath: <xxx>
    filter: "asd/train_1.*"

---
kind: Connection
type: s3
login:
password:
role: k2iam
url: <bucket name>